---
name: "Schedule: Sync labels"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync Labels
        uses: EndBug/label-sync@v2
        with:
          config-file: |
              https://raw.githubusercontent.com/dis-bzh/truecharts-.github/main/.github/labels.yaml
          token: "${{ secrets.DIS_TRUECHARTS_GITHUB_TOKEN }}"
          delete-other-labels: true
